GraniteHouseV2/Controllers/ApplicationTypeController.cs
using GraniteHouseV2.Data;
using GraniteHouseV2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace GraniteHouseV2.Controllers
{
    public class ApplicationTypeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ApplicationTypeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<ApplicationType> applicationTypes = _db.ApplicationType;

            return View(applicationTypes);
        }

        //GET - CREATE
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType applicationType)
        {
            _db.ApplicationType.Add(applicationType);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET - EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var applicationTypeObj = _db.ApplicationType.Find(id);
            if(applicationTypeObj == null)
            {
                return NotFound();
            }
            return View(applicationTypeObj);
        }

        // POST - EDIT
        [HttpPost]
        public IActionResult Edit(ApplicationType applicationType)
        {
            if (ModelState.IsValid)
            {
                _db.ApplicationType.Update(applicationType);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationType);
        }

        // GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var applicationTypeObj = _db.ApplicationType.Find(id);
            if (applicationTypeObj == null)
            {
                return NotFound();
            }
            return View(applicationTypeObj);
        }

        // POST - DELETE
        [HttpPost]
        public IActionResult DeleteConfirmed(int? applicationTypeId)
        {
            var applicationTypeObj = _db.ApplicationType.Find(applicationTypeId);
            if (applicationTypeObj == null)
            {
                return NotFound();
            }
            _db.ApplicationType.Remove(applicationTypeObj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

GraniteHouseV2/Controllers/CategoryController.cs
using GraniteHouseV2.Data;
using GraniteHouseV2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace GraniteHouseV2.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> categories = _db.Category;
            return View(categories);
        }

        //GET - CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Add(category);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //GET - EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryObj = _db.Category.Find(id);
            if (categoryObj == null)
            {
                return NotFound();
            }
            return View(categoryObj);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Update(category);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryObj = _db.Category.Find(id);
            if (categoryObj == null)
            {
                return NotFound();
            }
            return View(categoryObj);
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? CategoryId)
        {
            var categoryObj = _db.Category.Find(CategoryId);
            if (categoryObj == null)
            {
                return NotFound();
            }
            _db.Category.Remove(categoryObj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

GraniteHouseV2/Controllers/ProductController.cs
using GraniteHouseV2.Data;
using GraniteHouseV2.Models;
using GraniteHouseV2.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace GraniteHouseV2.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: ProductController
        public IActionResult Index()
        {
            IEnumerable<Product> productList = _db.Product.Include(x => x.Category).Include(a => a.ApplicationType);

            return View(productList);
        }

        // GET: ProductController/CreateEdit
        public IActionResult CreateEdit(int? id)
        {
            ProductVM productVM = new() {
                Product = new Product(),
                CategorySelectList = _db.Category.Select(i => new SelectListItem {
                    Text = i.Name,
                    Value = i.CategoryId.ToString()
                }),
                ApplicationTypeSelectList = _db.ApplicationType.Select(i => new SelectListItem { 
                    Text = i.Name,
                    Value = i.ApplicationTypeId.ToString()
                })
            };

            if (id == null)
            {
                return View(productVM);
            }

            productVM.Product = _db.Product.Find(id);
            if (productVM.Product == null)
            {
                return NotFound();
            }
            return View(productVM);
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateEdit(ProductVM productVM)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                string webRootPath = _webHostEnvironment.WebRootPath;

                if (productVM.Product.ProductId == 0)
                {
                    //Creating a Product
                    string uploadPath = webRootPath + AppConstants.ImagePath;
                    string fileName = Guid.NewGuid().ToString();
                    string fileExtension = Path.GetExtension(files[0].FileName);

                    // Copy file
                    using (var fileStream = new FileStream(Path.Combine(uploadPath, fileName + fileExtension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    productVM.Product.Image = fileName + fileExtension;

                    _db.Product.Add(productVM.Product);
                }
                else
                {
                    //Updating a product
                    var productFromDb = _db.Product.AsNoTracking().FirstOrDefault(x => x.ProductId == productVM.Product.ProductId);

                    if (productFromDb != null)
                    {
                        if (files.Count > 0)
                        {
                            string uploadPath = webRootPath + AppConstants.ImagePath;
                            string fileName = Guid.NewGuid().ToString();
                            string fileExtension = Path.GetExtension(files[0].FileName);

                            // Remove current file
                            var currentFilePath = Path.Combine(uploadPath, productFromDb.Image);

                            if (System.IO.File.Exists(currentFilePath))
                            {
                                System.IO.File.Delete(currentFilePath);
                            }

                            using (var fileStream = new FileStream(Path.Combine(uploadPath, fileName + fileExtension), FileMode.Create))
                            {
                                files[0].CopyTo(fileStream);
                            }

                            // Update the image path
                            productVM.Product.Image = fileName + fileExtension;
                        }
                        else
                        {
                            productVM.Product.Image = productFromDb.Image;
                        }

                        _db.Product.Update(productVM.Product);
                    }
                }

                _db.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            productVM.CategorySelectList = _db.Category.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.CategoryId.ToString()
            });

            productVM.ApplicationTypeSelectList = _db.ApplicationType.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.ApplicationTypeId.ToString()
            });

            return View(productVM);
        }

        // GET: ProductController/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0 )
            {
                return NotFound();
            }
            Product product = _db.Product.Include(p => p.Category).Include(a => a.ApplicationType)
                .Where(p => p.ProductId == id).FirstOrDefault();
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? productId)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;

            var productObj = _db.Product.Find(productId);
            if (productObj == null)
            {
                return NotFound();
            }
            _db.Product.Remove(productObj);
            _db.SaveChanges();

            // Remove image
            string uploadPath = webRootPath + AppConstants.ImagePath;
            var currentFilePath = Path.Combine(uploadPath, productObj.Image);

            if (System.IO.File.Exists(currentFilePath))
            {
                System.IO.File.Delete(currentFilePath);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

GraniteHouseV2/Views/Shared/_IndividualProductCard.cshtml
@model GraniteHouseV2.Models.Product

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ', '_')">
    <!-- Card -->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format(new System.Globalization.CultureInfo("en-US"), "{0:c0}", @Model.Price)</span> /sqft</label></div>
            <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@AppConstants.ImagePath@Model.Image" alt="Card image cap" />
            <div class="card-body p-1 px-3 row">
                <div class="col-6">
                    <span class="badge p-2 border w-100" style="background-color:lavenderblush">@Model.Category.Name</span>
                </div>
                <div class="col-6 border-0">
                    <span class="badge p-2 border w-100" style="background-color:aliceblue">@Model.ApplicationType.Name</span>
                </div>
                <div class="col-12 pt-2" style="font-size: 13px; text-align:justify">
                    <p>@Model.ShortDesc</p>
                </div>
                <div class="col-12 p-1">
                    <a asp-action="Details" asp-route-id="@Model.ProductId" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
                </div>
            </div>
        </div>
    </div>
</div>

GraniteHouseV2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using GraniteHouseV2.Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GraniteHouse v2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GraniteHouse</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                <div class="dropdown-divider"></div>
                                @if (User.IsInRole(AppConstants.AdminRole)) { 
                                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a>
                                }

                                @*<a class="dropdown-item" href="#">Something else here</a>*@
                            </div>
                        </li>
                        <li class="nav-item">
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(AppConstants.SessionCart) != null)
                            {
                                <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(AppConstants.SessionCart).Count;
                                    }
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(@count)
                                </a>
                            }
                            else
                            {
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(0)
                                </a>
                            }
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GraniteHouse v2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <link rel="stylesheet" href="~/sweetalert2/sweetalert2.css" />
    <link rel="stylesheet" href="~/summernote/summernote-bs4.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/sweetalert2/sweetalert2.all.js"></script>
    <script src="~/summernote/summernote.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>